name: hand_cricket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  logger: ^2.5.0
  flutter_cache_manager: ^3.4.1
  lottie: ^3.3.1
  dio: ^5.8.0+1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/hand_gestures/
    - assets/animation/

